### ISSUE TITLE
Agave on Nerd Fonts!?

### ISSUE THREAD

**Issue by aasutossh** [agarick/agave#13]
I was looking at Nerd Fonts collection on their website and they included Agave.
I didn't even knew that.
I feel good.

**Comment by blobject** [comment]
And so it is indeed! Much thanks to @xasx for the shout on the nerd-fonts issue tracker.

I'd like to take the opportunity to also give thanks to @jilen for mentioning agave to the codeface project, @dtzWill for packaging the font for nixos, and to various websites that mention the font.

I haven't looked around further so apologies if I fail to acknowledge anyone else who graciously helped to allow agave reach a larger audience. 

**edit:**  
Also appreciate **mikezackles** ' packaging efforts over at the arch linux AUR.

@braver also included this font in the "fonts" package for the atom editor, as well as showcased it on programmingfonts.org

**Comment by aasutossh** [comment]
I brag to my friends about agave, but never thought about bragging online, well, I'll try to brag whenever I can.

**Comment by blobject** [comment]
Thanks @aasutossh ! I'm so glad you like the font. All my love to everyone who's shown interest in agave.

**Comment by jozsefk9** [comment]
Best looking font on my screen! Thank you!

**Comment by blobject** [comment]
Closing, but please reopen if anyone sees fit.
