### ISSUE TITLE
remove P, V decorations

### ISSUE THREAD

**Issue by blobject** [agarick/agave#2]
Always felt that the quirks in the designs of "P" and "V" were too whimsical (the stroke on "V" was to distinguish it from logical_or; the cut off in "P" has no excuse).

https://github.com/Trabincle/agave-earth convinces me to revert back to plain, standard designs.

Seeing as modifications are sparse, this single edit will (finally) finalise version 009 of agave.

**Comment by blobject** [comment]
closed by https://github.com/agarick/agave/commit/7444f495caa1e6eafa7a89ad1cda4f45b5517c47

**Comment by velitasali** [comment]
Hey @agarick ,

I have been using `agave` on my favorite IDEs for a while now. And it surprised me that this font was not famous like other monospaced fonts. With that said, I have nothing to oppose the looks of V. I am using version 008. I don't know about P though. 

Great work!

**Comment by blobject** [comment]
Thank you very much for using agave, @velitasali 

I realised that the situation where one needs to distinguish "V" from logical_or is insignificant for most non-math-centric programmers, and even in such a situation, there is probably enough of a difference between the two glyphs in agave. (Though I haven't exactly tested it.) Also, I think a simpler and symmetric "V" is more consistent with the simplicity of the font as a whole. The same goes for "P". A stylisation of "P" would warrant consideration of similar styling in other glyphs, but the latter has been absent so far.

Again, I appreciate your attention towards agave, and any other suggestions or feedback would be welcome.

**Comment by velitasali** [comment]
@agarick Thank you. The only suggestion that I have is that the current state of the font should be preserved when there are big changes like thickness etc. The font is being rendered quite good on low DPI devices and easy to read.

**Comment by blobject** [comment]
I understand. I include the font files in this git tree, so every release (starting from 008) should always be accessible.
