### ISSUE TITLE
Wrong glyph for U+0263 LATIN SMALL LETTER GAMMA

### ISSUE THREAD

**Issue by dscorbett** [agarick/agave#20]
The glyph of U+0263 LATIN SMALL LETTER GAMMA would be fine for U+0194 LATIN CAPITAL LETTER GAMMA, but it is too tall for a lowercase letter. Here it is, with the existing U+0194 for comparison.
![ɣƔ](https://user-images.githubusercontent.com/1124347/94367944-8ffe0c00-00af-11eb-95dc-c13fa102d0a1.png)

**Comment by blobject** [comment]
Fixed in [release 24](https://github.com/agarick/agave/releases/tag/v24).

If you see any other odd glyphs or behavior, I'd be grateful for your continued help and will try to fix them right quick. If you see that the issues are fixed, please feel free to close them.
