### ISSUE TITLE
Missing bars on palatalized Komi letters

### ISSUE THREAD

**Issue by dscorbett** [agarick/agave#21]
The palatalized Komi letters U+0502..U+0505 and U+0508..U+050F should have horizontal bars upon their upwards curls. Currently, U+050C..U+050D have only the left half of the bar, and the rest have no bar at all.
![ԂԃԄԅԈԉԊԋԌԍԎԏ](https://user-images.githubusercontent.com/1124347/94369853-33541e80-00ba-11eb-830c-6bc9747e7535.png)
There are plenty of examples in the “на молодцовском алфавите 1920-тых годов” section of [this Komi book list](http://foto11.com/komi/docs/books/). In all the sans-serif text in those books, I only found two counterexamples, both on the title page of _Шонді југӧр_ (1926) in “ЛЫԂԂӦГПАНЫԌ”, though the rest of the sans-serif text within that book follows the general pattern. Here is [another Komi book list](http://wiki.komikyv.org/index.php/%D0%9A%D0%BE%D0%BC%D0%B8_(%D0%B7%D1%8B%D1%80%D1%8F%D0%BD%D0%B0%D0%BB%D3%A7%D0%BD)_%D0%BD%D0%B5%D0%B1%D3%A7%D0%B3_1918%E2%80%931938).

**Comment by blobject** [comment]
Thanks for bringing this to my attention. I know next to nothing about the Komi script and I should have looked into it more during the design process. (Actually, the same goes for almost all the non-ASCII scripts.)

_brief look:_

I skimmed through the book covers of the first book list. As you said, the sans-serif titles also include the horizontal bars. So the bar definitely is not a remnant of serif stylisation, as I suspected at first. Do you perhaps have further information regarding the Komi script in sans-serif format or their digitisation? I cannot find histories regarding this topic online.

_guess about purpose and correctness:_

Maybe the bar has to do with distinguishing upper and lower cases? What I did was just squish the lower case letters (with the exception of dje, whose design did strike me as awkward while I was drawing it), but I now wonder if the squishing is not totally correct or sufficient.

_design references:_

On the other hand, during design, I did refer to other sans-serif monospace fonts and all the ones I've seen did not have horizontal bars. Even Arial does not include bars. Courier (which I guess is a serif font) does include bars, but only the left part of the bar. Here is a screenshot:
![nje](https://user-images.githubusercontent.com/15623001/94374637-ea2dba00-010d-11eb-90f0-db259c957451.png)

_what to do?_

So I'm wondering if this absence of bars has to do with space constraints and making more legible these digraphs that need to be fit into a single glyph.

Do you think this is something we can let pass or is it wrong in principle?

---

**edit:** Well, maybe they're not digraphs. I'm not sure about that, but the bars _would_ make things look a bit busier.

**Comment by dscorbett** [comment]
I recommend that the glyphs be squished a bit more to fit the bar or removed from the font.

Many modern fonts omit the bar. I suspect this is because the Molodtsov alphabet was only used for about 10 years almost 100 years ago: no one uses it anymore, so no one cares enough to report the problem. (Well, except me.) It’s not only monospace fonts that omit the bar, so it’s not just a pragmatic way to fit the glyph in a narrow width. Given the modern irrelevance of these letters, a perfectly fine solution is to remove them from the font; but in a font that does support them, they should in principle include the bar.

Both uppercase and lowercase letters have the bar, so it’s not about distinguishing case.

I don’t know what inspired Molodtsov to adopt this curve as a common subgrapheme, but I can speculate. My guess is that it is a reduced form of the soft sign ⟨ь⟩, just as ⟨њ⟩ is a more transparent ligature of ⟨нь⟩. This is supported by figures 3–5 of [L2/00-182](https://www.unicode.org/L2/L2000/00182-n2224.pdf), where the curve is rendered as a very, very small ⟨ь⟩-like loop. Also, one of the books in the second list (unfortunately I forgot to note which one) has a handwritten cursive ⟨ԋ⟩ where the curve doesn’t point straight up but curves around to point leftwards. However, I don’t really know. There’s not much information out there about this alphabet in English. I found [this Russian article](https://www.gramota.net/articles/issn_1997-2911_2014_10-2_38.pdf), but it just says there is a curve without explaining why.

Squishing is totally correct and sufficient. (See also U+01CA LATIN CAPITAL LETTER NJ where Agave’s squished glyph looks fine.) The old books’ proportional glyphs generally only leave a tiny gap between the left part of the bar and the main part of the letter. It’s not like in Arial where the curve takes half the width. For example, [this book](https://fennougrica.kansalliskirjasto.fi/bitstream/handle/10024/87472/kpv_3_1626_1932.pdf?sequence=1) has the word “ԎЕХԊІКА” in the title. On the cover, the curves are just small rightwards protrusions. On the title page, the curves are very narrow. This is evidence that the curve (even in fonts where it is not really a curve) was never a visually prominent part of the design and is very squishable.

To be clear, almost all of the barless glyphs are in fancy titling fonts or in handwriting. The overwhelming majority of normal body text uses a horizontal bar. In serif fonts the bar is sometimes a normal serif and sometimes a heavy slab serif, whereas in sans-serif fonts it is consistently a slab serif. So I don’t think it is appropriate for _this_ font to emulate those few exceptions.

**Comment by blobject** [comment]
That's excellent information, and thanks also for your speculation. I clearly didn't do my homework here, and in fact assumed that the script was being used widely today as part of "the Cyrillic script", seeing as the font-making program just lists the Komi glyphs as a continuation of the rest of the Cyrillic glyphs.

Well, I should probably remove the Komi glyphs from agave since they are beyond my experience and most likely do/will not fall within the target scope. I will remove them after reading up a bit more about Cyrillic and Unicode.

Oh, and by "squished" I was referring to vertical shortening, not horizontal. As in, the lower case glyphs were shortened, stubby versions of their upper case counterparts.

In any case, please continue with your valuable auditing and create more issues if you'd like :-D It's very helpful.

**Comment by blobject** [comment]
Fixed in https://github.com/agarick/agave/releases/tag/v25 - komi glyphs removed
