### ISSUE TITLE
U+027F LATIN SMALL LETTER REVERSED R WITH FISHHOOK should have a descender

### ISSUE THREAD

**Issue by dscorbett** [agarick/agave#23]
U+027F LATIN SMALL LETTER REVERSED R WITH FISHHOOK should have a descender: [the code chart](https://www.unicode.org/charts/PDF/U0250.pdf) says “preferred presentation is with a descender”.

**Comment by blobject** [comment]
Improved in https://github.com/agarick/agave/releases/tag/v25

**Comment by blobject** [comment]
improved and fixed, i mean :-)

**Comment by dscorbett** [comment]
U+027F gained a descender but lost a fishhook. Its top should be rounded like U+027E LATIN SMALL LETTER R WITH FISHHOOK.

**Comment by blobject** [comment]
Doh! Nice catch. Should be fixed in https://github.com/agarick/agave/releases/tag/v26
