### ISSUE TITLE
Questionable glyph for U+02AC LATIN LETTER BILABIAL PERCUSSIVE

### ISSUE THREAD

**Issue by dscorbett** [agarick/agave#24]
In all other fonts that I know of, U+02AC LATIN LETTER BILABIAL PERCUSSIVE is a ⟨w⟩ above another ⟨w⟩. Is this rectilinear glyph intentional?
![ʬ](https://user-images.githubusercontent.com/1124347/94493754-7d70f900-01bb-11eb-9b8b-2e33feaf5c9f.png)

**Comment by blobject** [comment]
I can't remember exactly, but it must have come about through laziness. I'll fix it.

**Comment by blobject** [comment]
Fixed in https://github.com/agarick/agave/releases/tag/v25
