### ISSUE TITLE
𝑛-ary operators are too short

### ISSUE THREAD

**Issue by dscorbett** [agarick/agave#27]
<var>n</var>-ary mathematical operators should be taller than normal operators: U+220F N-ARY PRODUCT, U+2210 N-ARY COPRODUCT, and U+2211 N-ARY SUMMATION should descend below the baseline. The current glyph for U+2210 would be appropriate for U+2A3F AMALGAMATION OR COPRODUCT.

**Comment by blobject** [comment]
You're right, I'll make their baselines and heights consistent with those of ascii's parens and brackets.

I should also do the same for ceiling and floor (u2308 - u230b)

**Comment by blobject** [comment]
Fixed in https://github.com/agarick/agave/releases/tag/v27
including heights of ceiling & floor.
