### ISSUE TITLE
U+2201 COMPLEMENT looks like ⟨C⟩

### ISSUE THREAD

**Issue by dscorbett** [agarick/agave#28]
U+2201 COMPLEMENT looks identical to U+0043 LATIN CAPITAL LETTER C. It should look more stretched, as in [`\complement` in LaTeX](http://tug.ctan.org/info/symbols/comprehensive/symbols-a4.pdf#page=254).

**Comment by blobject** [comment]
Fixed in https://github.com/agarick/agave/releases/tag/v27
