### ISSUE TITLE
powerline glyphs?

### ISSUE THREAD

**Issue by dtzWill** [agarick/agave#3]
Hi! Long-time fan of this wonderful font!

Have you considered adding the powerline symbols/glyphs to this font?

Fiddling with fontconfig is a pain in the best of circumstances, and would be wonderful to see official support for this!  Not sure how much work this involves so I apologize if it's a lot of work-- but I'd be interested in hearing your thoughts on this regardless!

Thanks, and thanks for this great font!

**Comment by blobject** [comment]
Hi @dtzWill thanks for the comment and issue.

I took a brief look around and it seems that we would need particular glyphs in the unicode range u+e0a0 to u+e0??.
- https://apw-bash-settings.readthedocs.io/en/latest/fontpatching.html
- https://github.com/powerline/powerline/issues/4

I am not familiar with powerline myself, but perhaps the following glyphs will do:
- u+e0a0 (branch)
- u+e0a1 (line number)
- u+e0a2 (lock)
- u+e0b0 (filled right triangle)
- u+e0b1 (outlined right triangle)
- u+e0b2 (filled left triangle)
- u+e0b3 (outlined left triangle)

If I'm missing something, I would love to get your input, as well as that of other powerline users.

Trying out powerline and testing things out (like https://github.com/powerline/powerline/issues/14) could take some time, but I'm willing to work on this issue as soon as I can. This weekend perhaps.

**Comment by dtzWill** [comment]
Wow, thank you! I've put together a fontconfig-based solution which now that it's in place lets me use agave as my terminal font to my heart's content, without strange glyphs appearing :).  It's not aligned quite right (or sized wrong or w/e), not sure what goes into making things work right in that regard.  Hopefully not much trouble! Solution basically pushes powerline's "PowerlineSymbols" font to be searched first, to pick up the powerline symbols, and "fallback" to agave or whatever.  Haha, based on powerline's fontconfig snippet.  https://github.com/dtzWill/nur-packages/blob/master/modules/powerline-symbols.nix .

I am curious but have no idea how this compares to the font patching solutions, I'd perhaps naively guess it's about the same.  Dunno :).

Here's hoping it's a small count of geometric shapes, at least if that means it's less trouble to support :).

Thanks for your quick response and let me know if I can help with testing or feedback or ... whatever :).  Honestly I made the issue partially to be sure you knew you made something folks use and enjoy and want to integrate -- no worries if you can't get to it too soon.

**Comment by blobject** [comment]
I looked through your fontconfig solution (awesome that you're using nix by the way; I use guix myself :-), then browsed `PowerlineSymbols.otf` using FontForge, and saw that, indeed, its set of glyphs consists of the 7 listed above, in addition to the "not defined" glyph and the "full block" glyph which agave already has.

Designing the 7 new glyphs should not be difficult at all, and it would be a pleasure to directly respond to your request. Once I've added the glyphs and had my go at testing them a bit, I'll release an updated font file.

**Comment by blobject** [comment]
Just pushed a pre-release containing the new glyphs. https://github.com/agarick/agave/releases/tag/v010

I'm still in the midst of testing it. Termite and xterm are refusing to display the agave glyphs, but something like Libreoffice displays them fine. I have yet to install powerline for testing.

Perhaps you'd like to try it out as well, @dtzWill . If you do, I'd appreciate knowing which application you used for powerline (terminal, gvim, etc.) and whether it works/fails. Thanks.

**Comment by dtzWill** [comment]
Hi! Thank you! :)

Tried it (termite, st) and mostly looks good but one of the symbols seems backward:

![agave_010_powerline](https://user-images.githubusercontent.com/817330/52926508-a8b31700-32fb-11e9-9f7f-f65c0fda1eba.png)

the "right_sep" should be facing the other way.

I'm not sure of the details involved, at all :innocent:, but the triangles are intended (err, I think?) to line up with ... however the normal line height? So:

![agave_triangle_height](https://user-images.githubusercontent.com/817330/52926704-8a015000-32fc-11e9-98b6-00d1c9b8bed0.png)

It looks like there's a gap on the left side (of the triangles shown here), not sure what contributes to that.
If these don't match well to font technicalities (I couldn't say), looking at the values/metrics/idk from other fonts for these would clarify -- IIRC another font had to go through a bit of guess-and-check and hopefully that can be avoided! :).

**Comment by dtzWill** [comment]
Text that you can 'cat' or something in your terminal when testing (as used in screenshot above, and from airline's help):

```
  " powerline symbols
  let g:airline_left_sep = ''
  let g:airline_left_alt_sep = ''
  let g:airline_right_sep = ''
  let g:airline_right_alt_sep = ''
  let g:airline_symbols.branch = ''
  let g:airline_symbols.readonly = ''
  let g:airline_symbols.linenr = '☰'
  let g:airline_symbols.maxlinenr = ''

```

**Comment by dtzWill** [comment]
Updated fixed the backwards glyph, \o/ thanks!

**Comment by blobject** [comment]
I'm glad the triangle is turning the correct way now :-D.

It seems the alignment issue is pretty ubiquitous for monospace fonts, and I'm still trying to see if there is a really clean solution. For instance, as other fonts are doing, we could tweak the metrics and do some "guess-and-check", as you've mentioned, but I wonder if the alignment would still break if the underlying application modifies its own line-height/metrics configuration.

In any case, I'll do a tentative metrics-tweak soon, hopefully this weekend, but a proper fix demands a bit more time. Helpful info or a PR from anyone would be much appreciated.

**Comment by blobject** [comment]
Updated the pre-release again: https://github.com/agarick/agave/releases/tag/v010

Apologies for the wait; I finally managed to get a virtual linux instance running that's allowing for more consistent testing.

Anyway, the change made is: the triangular glyphs have been stretched upwards (beyond the glyph box) by 256 units. According to some issues on other fonts, these glyphs adopt the maximum bounds of the entire font, and ignore their own box for some reason. In the case of agave, since it contains some glyphs with diacritics that protrude upward by about 256, the triangular powerline glyphs have been stretched to reflect these dimensions.

On my Fedora Workstation 29 instance with Gnome, and testing on gnome-terminal 3.30.1, these changes look good (tried sizes 12, 24, and 48).

I would appreciate feedback on how powerline looks now on your usual work spaces.

**Comment by blobject** [comment]
@dtzWill : By the way, I noticed that you'd packaged agave for Nix. Thank you very much for that.

In this latest pre-released, I also shifted the `src/` structure around a bit; I hope that doesn't break your nix script.

**Comment by blobject** [comment]
Just pushed a slight change. Width has been stretched a bit as well - I remembered that a few glyphs have negative left-bearing and a few others have negative right-bearing. Hopefully, this change fixes the slight side gap issue as seen in a screenshot above.

As tested on fedora's gnome-terminal, the negative shift becomes noticeable at huge sizes, but negligible at small size (12pt).

**Comment by dtzWill** [comment]
On Thu, 14 Mar 2019 14:40:03 +0000 (UTC), agaric <notifications@github.com> wrote:
> Just pushed a slight change. Width has been stretched a bit as well - I remembered that a few glyphs have negative left-bearing and a few others have negative right-bearing. Hopefully, this change fixes the slight side gap issue as seen in a screenshot above.

Yes! That was only minor, but thank you and I think it's perfect now!

Certainly looks perfect in normal usage :D.

Hype hype re:bold, presently I'm giving freetype2 permission to
syntethically 'embolden' for higher weights (in practice just for bold).

It kinda makes glyphs 'jump' a bit, but it works better than I
expected/feared :).

Anyway thank you so much for adding the powerline glyphs! <3

**Comment by blobject** [comment]
You're very welcome. Glad to hear powerline's looking better.

I'm still chewing over plans for bold and italic. They weren't in my original "idea" for the font so movement has been a bit slow. In the mean time, please feel free to leave other comments or requests. If any aspect of any glyph is causing eye-ache (eick?), for powerline or otherwise, I'd appreciate the feedback.

Also if you're happy with the resolution of this issue, feel free to close it.

**Comment by dtzWill** [comment]
:heart:
