### ISSUE TITLE
U+0462 CYRILLIC CAPITAL LETTER YAT has misplaced crossbar

### ISSUE THREAD

**Issue by dscorbett** [agarick/agave#31]
The crossbar of U+0462 CYRILLIC CAPITAL LETTER YAT should go through the vertical stroke, not on top of it.
![Ѣ](https://user-images.githubusercontent.com/1124347/95024958-37e97b80-0654-11eb-8668-2325742d962d.png)

**Comment by blobject** [comment]
Fixed in https://github.com/agarick/agave/releases/tag/v29
