### ISSUE TITLE
Stroke width of U+23B7 RADICAL SYMBOL BOTTOM

### ISSUE THREAD

**Issue by dscorbett** [agarick/agave#44]
The stroke width of U+23B7 RADICAL SYMBOL BOTTOM is wider than that of other radical symbol pieces, which are unified with the box drawing symbols U+2502 and U+250C according to [L2/00-159](https://www.unicode.org/L2/L2000/00159-ucsterminal.txt). Here it is below U+2502.
![│␤⎷](https://user-images.githubusercontent.com/1124347/96531650-227d6f80-1258-11eb-9e6b-979f89782784.png)
U+23B7 does, however, have the same width as U+23AE INTEGRAL EXTENSION, which L2/00-159 lists as an alternative to U+2502, but I think using U+2502 is preferable, since U+2502 has the same stroke width as U+250C for the corner piece, for which L2/00-159 lists no alternative.

**Comment by blobject** [comment]
Fixed in https://github.com/blobject/agave/releases/tag/v32

All the multiline math stuff (like braces and integrals and their extensions) now have the same width as eg. u2502
