### ISSUE TITLE
Braille patterns have confusing spacing

### ISSUE THREAD

**Issue by dscorbett** [agarick/agave#45]
The side bearings of the braille patterns are too small relative to the internal spacing between dots. For example, U+2831 is hard to distinguish from <U+2808, U+2806>. [Table 703.3.1 of the ADA Accessibility Guidelines](https://www.access-board.gov/guidelines-and-standards/buildings-and-sites/about-the-ada-standards/ada-standards/chapter-7-communication-elements-and-features) indicates the proper ratios.
![⠱⠈⠆](https://user-images.githubusercontent.com/1124347/96598624-0eb82480-12bd-11eb-8f0f-5792d3bb8c54.png)

**Comment by blobject** [comment]
Improved (Fixed?) in https://github.com/blobject/agave/releases/tag/v32

Per the guidelines:
- The dot has been made circular
- Side-bearings are wider to respect horizontal-inter-glyph spacing
- Vertically, the dots are spaced out such that between two vertically positioned braille glyphs, the guidelines' ratio is respected. However, the vertical-inter-dot ratio is a bit off, and the vertical-inter-glyph ratio of two glyphs with only 3 rows of dots (as in the examples in the guidelines) is impossible to achieve given the box dimensions.
