### ISSUE TITLE
U+23AF HORIZONTAL LINE EXTENSION is too low

### ISSUE THREAD

**Issue by dscorbett** [agarick/agave#48]
The names list says U+23AF HORIZONTAL LINE EXTENSION is “used for extension of arrows”, so it should be aligned with horizontal arrows.
![←⎯→](https://user-images.githubusercontent.com/1124347/97093061-165a2f00-1617-11eb-85d0-c965ffe6a22c.png)

**Comment by blobject** [comment]
Fixed in https://github.com/blobject/agave/releases/tag/v34
