### ISSUE TITLE
SUGGESTION: Link "latest" to current release

### ISSUE THREAD

**Issue by kajukenbo** [agarick/agave#50]
Hi bud.

Great work as always.
I jump in every few days to get an updated copy and see if I can spot / appreciate the differences.

To that end, is there a way to link "latest" somehow straight to a download / zip?
I pull up latest then scroll down to "Assets" to get a TTF or just pull the master.zip from the home page.

Is pulling master.zip the recommended way to stay up-to-date or can you somehow link "latest" to the current TTF?

Thanks!

**Comment by alexeyten** [comment]
Assuming that file names will not change, here are links to latest release files:
```
https://github.com/blobject/agave/releases/latest/download/Agave-Regular.ttf
https://github.com/blobject/agave/releases/latest/download/Agave-Bold.ttf
```

[Documentation](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/linking-to-releases)

**Comment by blobject** [comment]
Hi kajukenbo, that's a good suggestion. In the next release, I'll try to make the readme a bit more accessible in this regard.

The links provided by alexeyten also work well, and the filenames shouldn't change in the foreseeable future.

If you use git, and are willing to keep a copy of this project on your disk, you can also pull it every now and then and the font files under `dist/` should get up to date.

**Comment by blobject** [comment]
I've added links to the latest Regular and Bold font files at the top of the README. I hope you find that easier to get to. Releases (which contain snapshots of the font files at specific versions) will continue to be posted as well.
