### ISSUE TITLE
Visual Studio Community 2019 renders Agave poorly.

### ISSUE THREAD

**Issue by iozsaygi** [agarick/agave#9]
After i installed the new version of agave from [here](https://github.com/agarick/agave/tree/master/dist) it works in VSCommunity but it renders the font poorly. (I guess it might be some anti-aliasing problem with VSCommunity, not sure)

Here is the example screenshot.
![example](https://user-images.githubusercontent.com/36489581/63917911-4a9e8380-ca44-11e9-8199-e4185b091506.png)

The font size is 10 in this picture.
Thanks.

**Comment by blobject** [comment]
Thanks for creating the issue. I have been looking into this after https://github.com/agarick/agave/issues/7 and have made some progress.

In the [latest release (version 12)](https://github.com/agarick/agave/releases), agave is now auto-hinted and auto-instructed (using FontForge), and things look a lot better on VSCommunity now.

I can't say I completely understand what I'm doing or how "hinting" really works, but I suspected maybe adding hinting instructions would help, and followed the FontForge wiki (https://github.com/fontforge/fontforge/wiki/How-TT-Hinting-Works) to apply a sweeping generic autohint on all the glyphs. To my pleasant surprise, the resulting font looks much smoother.

So far, I have done very little testing with the new version, and cannot guarantee that previously good behavior will not break. (If things do break, please let me know by creating additional issues.) But I did try the new version on the few Windows and Linux applications that I have, and things seem normal. Of course, rendering may not be perfect and comparisons + adjustments are in order. But I am hopeful that agave's geometric simplicity and consistency would give FontForge's autohinter little cause for protest.

Anyway, I hope the release helps and would appreciate your feedback.

**Comment by iozsaygi** [comment]
Hey, sorry for late reply.
I downloaded and installed the version 12 and it works perfectly fine with Visual Studio Community 2019 right now. (At least for me)
Thank you so much for creating awesome content. Finally i can use Agave inside the IDE that i use most.
Since the new version solves my problem, i am going to close this issue.
Thanks. 

**Edit:** I am really looking forward the get agave with new types like italic, medium, bold etc. And i do know that you are working on that so good luck with your work!

**Comment by blobject** [comment]
Super happy it's working for you. Also really glad that this issue was created. -- Wish I'd known about it sooner but I had seldom used Vindows until now.

I keep postponing the italic and bold but also trying my best to levitate their priority.

Thank you as always for appreciating agave.

**Comment by blobject** [comment]
Reopened by https://github.com/agarick/agave/issues/14#issuecomment-658497365 but turns out, if that issues is indeed fixed, this was a false alarm.
